### ISSUE TITLE
Cannot re-enable auto correction in version 0.5.1

### ISSUE THREAD

**Issue by amourchaleur** [rugk/unicodify#77]
## Bug description
After the update to the latest version 0.5.1, not able to re-enable unicode autocorrection.

## Steps to reproduce
When I tried clicking on the checkbox, it just doesn't checked at all. Auto correction also does not turn on.

### Actual behavior
No reaction to checkbox after clicking on it.

Operating system and version: 
Browser and version: Thunderbird 91.11.0 (64-bit)
Add-on version: 0.5.1

**Comment by tdulcet** [comment]
Thanks for the bug report! I did not catch this until after publishing the v0.5.1 update (the checkbox works fine in Firefox), but it is actually a Thunderbird regression, so I filed [bug 1780977](https://bugzilla.mozilla.org/show_bug.cgi?id=1780977). If they do not fix that soon, I will release another update with a workaround (see https://github.com/rugk/unicodify/pull/72/commits/a8b95bbea3b6030dd620d290e070900eff9ca67c). Sorry for the inconvenience. See [bug 1777183](https://bugzilla.mozilla.org/show_bug.cgi?id=1777183) for why the autocorrect feature was disabled by default in this update (another regression in Thunderbird 102).

**Comment by tdulcet** [comment]
I just published v0.5.2 on ATN which works around bug 1780977 to allow the autocorrection feature to be reenabled. This also fixes a regression from #37 to allow users to undo the smart quote autocorrections.

@amourchaleur  - You should automatically get the update within 24 hours or you can force it from the Add-ons manager.

**Comment by rugk** [comment]
@tdulcet If you publish such versions, BTW, it would be great if you could [at least also tag the corresponding commit you've used](https://github.com/rugk/unicodify/tags). The tags here are heavily outdated and still show v0.1.

**Comment by tdulcet** [comment]
As I mentioned above, this was fixed by https://github.com/rugk/unicodify/pull/72/commits/a8b95bbea3b6030dd620d290e070900eff9ca67c, which is part of #72. I am not sure if I can tag commits in a PR, but the actual commit was the latest in #72 (https://github.com/rugk/unicodify/pull/72/commits/8917637a3431535c604ca10e802478b847a5970d).

**Comment by rugk** [comment]
> I am not sure if I can tag commits in a PR,

Git tags are always possible, but yeah they may only be visible in your fork and not mine. Anyway. nevermind. Next time.
